# Config generated for ClaimChunk version @PLUGIN_VERSION@
# For more information about all these options, please visit the wiki page:
# https://github.com/cjburkey01/ClaimChunk/wiki/Configuration-File

basic:
  disablePermissions: false
  checkForUpdates: true

log:
  debugSpam: false
  debug: false
  anonymousMetrics: true

titles:
  useTitlesInsteadOfChat: true
  useActionBar: true
  titleFadeInTime: 20
  titleStayTime: 140
  titleFadeOutTime: 20

colors:
  infoColor: GOLD
  errorColor: RED

chunks:
  maxChunksClaimed: 50
  particlesWhenClaiming: true
  hideAlertsForVanishedPlayers: true
  automaticUnclaimSeconds: -1
  unclaimCheckIntervalTicks: 1200
  displayNameOfOwner: true
  defaultSendAlertsToOwner: true
  maxPerListPage: 5
  disabledWorlds: []

chunkOutline:
  name: 'SMOKE_LARGE'
  durationSeconds: 10
  spawnsPerSecond: 2
  particlesPerSpawn: 3
  heightRadius: 2 # TODO

protection:
  blockedCmds: []
  disableOfflineProtect: false

worldguard:
  allowClaimsInRegionsByDefault: true
  allowClaimingInNonGuardedWorlds: true
  allowAdminOverride: true

economy:
  useEconomy: true
  claimPrice: 100.0
  unclaimReward: 10.0
  firstFreeChunks: 0

data:
  saveDataIntervalInMinutes: 10
  keepJsonBackups: true
  minBackupIntervalInMinutes: 120
  deleteOldBackupsAfterMinutes: 10080

database:
  useDatabase: false
  groupRequests: true
  convertOldData: true
  hostname: '127.0.0.1'
  port: 3306
  database: 'MyServer'
  username: 'root'
  password: 'root'
  printDebug: false
  useSsl: false
  allowPublicKeyRetrieval: false
